### ISSUE TITLE
Where is the http_substitutions_filter module?

### ISSUE THREAD

**Issue by HinataKato** [byjg/docker-nginx-extras#2]
You mentioned [here](https://github.com/byjg/docker-nginx-extras/blob/master/README.md#third-party-modules) that ngx_http_substitutions_filter_module is supported, but I checked it with nginx -V | grep --color stub_status_module and it is not there, neither is the dockerfile, do I need to modify the dockerfile myself?

**Comment by byjg** [comment]
Hello, you're right. The module `ngx_http_substitutions_filter_module` wasn't installed. 

```
nginx -V 2>&1 | tr ' ' '\n' | grep 'ngx_http_substitutions_filter_module'
```

I created PR #3 with the fix and by the end of the week, I'll create a version.

**Comment by HinataKato** [comment]
> Hello, you're right. The module `ngx_http_substitutions_filter_module` wasn't installed.
> 
> ```
> nginx -V 2>&1 | tr ' ' '\n' | grep 'ngx_http_substitutions_filter_module'
> ```
> 
> I created PR #3 with the fix and by the end of the week, I'll create a version.

Thank you :), is there any workaround now? Like fork it and let GitHub Action compile the image?

**Comment by byjg** [comment]
For now, you can pull the `master` tag:

```
docker pull byjg/nginx-extras:master
```

The `master` tag has the module you want. 

I am unable to generate the proper tag `latest` and 1.21 now. But I'll do it soon.

**Comment by HinataKato** [comment]
> For now, you can pull the `master` tag:
> 
> ```
> docker pull byjg/nginx-extras:master
> ```
> 
> The `master` tag has the module you want.
> 
> I am unable to generate the proper tag `latest` and 1.21 now. But I'll do it soon.

So, any update?

**Comment by HinataKato** [comment]
> Yes, tag 1.21 was created - https://github.com/byjg/docker-nginx-extras/releases/tag/1.21
> 
> The current tag is 1.23.

okay, thank you :)
